/**
 * TrustMart Full Deployment Script – Kite Chain Testnet
 * Deploys ALL 5 contracts and wires them together
 *
 * Run: npx hardhat run scripts/deploy.js --network kite_testnet
 */

const { ethers } = require("hardhat");
const fs   = require("fs");
const path = require("path");

const c = { green:"\x1b[32m", cyan:"\x1b[36m", yellow:"\x1b[33m", bold:"\x1b[1m", reset:"\x1b[0m" };
const ok   = (m) => console.log(`${c.green}✅ ${m}${c.reset}`);
const info = (m) => console.log(`${c.cyan}ℹ️  ${m}${c.reset}`);
const step = (m) => console.log(`\n${c.bold}${c.cyan}▶ ${m}${c.reset}`);
const addr = (l, a) => console.log(`   ${l}: ${c.cyan}${a}${c.reset}`);

function copyABIs(deployedAddresses) {
  const contracts = ["ProductRegistry","EscrowOrder","DisputeResolver","ReputationSystem","AttestationRegistry"];
  const aDir = path.join(__dirname, "../artifacts/contracts");
  const fDir = path.join(__dirname, "../frontend/abis");
  if (!fs.existsSync(fDir)) fs.mkdirSync(fDir, { recursive: true });

  for (const name of contracts) {
    const p = path.join(aDir, `${name}.sol/${name}.json`);
    if (fs.existsSync(p)) {
      const artifact = JSON.parse(fs.readFileSync(p, "utf8"));
      fs.writeFileSync(path.join(fDir, `${name}.json`), JSON.stringify({ abi: artifact.abi }, null, 2));
      ok(`ABI: ${name}.json`);
    } else {
      console.warn(`⚠️  Artifact missing: ${name}`);
    }
  }

  // Write deployed addresses for frontend
  fs.writeFileSync(
    path.join(__dirname, "../frontend/config/deployedAddresses.json"),
    JSON.stringify(deployedAddresses, null, 2)
  );

  // Write agent .env snippet
  const agentEnvSnippet = `
# Auto-generated by deploy.js — paste into agent/.env
ATTESTATION_REGISTRY_ADDRESS=${deployedAddresses.contracts.AttestationRegistry}
ESCROW_ORDER_ADDRESS=${deployedAddresses.contracts.EscrowOrder}
PRODUCT_REGISTRY_ADDRESS=${deployedAddresses.contracts.ProductRegistry}
DISPUTE_RESOLVER_ADDRESS=${deployedAddresses.contracts.DisputeResolver}
KITE_RPC_URL=https://rpc-testnet.gokite.ai/
`;
  fs.writeFileSync(path.join(__dirname, "../agent/.env.contracts"), agentEnvSnippet.trim());
  ok("agent/.env.contracts written (paste into agent/.env)");
}

async function main() {
  console.log(`\n${c.bold}${"═".repeat(54)}`);
  console.log(`  🛒  TrustMart Full Deployment – Kite Chain`);
  console.log(`${"═".repeat(54)}${c.reset}\n`);

  const [deployer] = await ethers.getSigners();
  const network    = await ethers.provider.getNetwork();
  const balance    = await deployer.getBalance();

  info(`Network  : ${network.name} (chainId: ${network.chainId})`);
  addr("Deployer", deployer.address);
  info(`Balance  : ${ethers.utils.formatEther(balance)} KITE`);

  if (balance.lt(ethers.utils.parseEther("0.1"))) {
    console.warn("⚠️  Low balance — you need at least 0.1 KITE for deployment");
  }

  const FEE_RECEIVER = process.env.FEE_RECEIVER_ADDRESS || deployer.address;

  // 1 — ProductRegistry
  step("Deploying ProductRegistry");
  const PR = await (await ethers.getContractFactory("ProductRegistry")).deploy(FEE_RECEIVER);
  await PR.deployed(); ok(`ProductRegistry → ${PR.address}`);

  // 2 — EscrowOrder
  step("Deploying EscrowOrder");
  const EO = await (await ethers.getContractFactory("EscrowOrder")).deploy(PR.address, FEE_RECEIVER);
  await EO.deployed(); ok(`EscrowOrder → ${EO.address}`);

  // 3 — DisputeResolver
  step("Deploying DisputeResolver");
  const DR = await (await ethers.getContractFactory("DisputeResolver")).deploy(EO.address, deployer.address);
  await DR.deployed(); ok(`DisputeResolver → ${DR.address}`);

  // 4 — ReputationSystem
  step("Deploying ReputationSystem");
  const RS = await (await ethers.getContractFactory("ReputationSystem")).deploy(EO.address, PR.address);
  await RS.deployed(); ok(`ReputationSystem → ${RS.address}`);

  // 5 — AttestationRegistry (NEW — AI agent writes here)
  step("Deploying AttestationRegistry");
  const AR = await (await ethers.getContractFactory("AttestationRegistry")).deploy();
  await AR.deployed(); ok(`AttestationRegistry → ${AR.address}`);

  // ── Wiring ────────────────────────────────────────────
  step("Wiring contracts");

  let tx;
  tx = await EO.setDisputeResolver(DR.address);   await tx.wait(1); ok("EO.setDisputeResolver ✓");
  tx = await PR.authorizeContract(EO.address, true);  await tx.wait(1); ok("PR authorized EscrowOrder ✓");
  tx = await PR.authorizeContract(RS.address, true);  await tx.wait(1); ok("PR authorized ReputationSystem ✓");

  // Note: setAuthorizedAgent is called AFTER agent wallet is set up
  // Run: npx hardhat run scripts/set-agent.js --network kite_testnet
  info("Note: Run set-agent.js after configuring AGENT_PRIVATE_KEY");

  // ── Summary ───────────────────────────────────────────
  const deployed = {
    network: network.name, chainId: network.chainId,
    deployer: deployer.address, feeReceiver: FEE_RECEIVER,
    deployedAt: new Date().toISOString(),
    contracts: {
      ProductRegistry:     PR.address,
      EscrowOrder:         EO.address,
      DisputeResolver:     DR.address,
      ReputationSystem:    RS.address,
      AttestationRegistry: AR.address,
    },
  };

  console.log(`\n${c.bold}${c.green}${"═".repeat(54)}`);
  console.log(`  ✅  ALL 5 CONTRACTS DEPLOYED`);
  console.log(`${"═".repeat(54)}${c.reset}\n`);
  console.log(JSON.stringify(deployed.contracts, null, 2));

  // Copy ABIs + save addresses
  step("Copying ABIs → frontend/abis/");
  copyABIs(deployed);

  // Save deployment log
  const logDir = path.join(__dirname, "../deployments");
  if (!fs.existsSync(logDir)) fs.mkdirSync(logDir);
  fs.writeFileSync(path.join(logDir, `${network.chainId}-${Date.now()}.json`), JSON.stringify(deployed, null, 2));
  ok("Deployment log saved");

  console.log(`\n${c.bold}${c.yellow}📋 Next steps:${c.reset}`);
  console.log(`  1. cp frontend/.env.example frontend/.env.local`);
  console.log(`     → Fill in contract addresses (auto-written to deployedAddresses.json)`);
  console.log(`  2. cat agent/.env.contracts → paste into agent/.env`);
  console.log(`  3. Add ANTHROPIC_API_KEY + AGENT_PRIVATE_KEY to agent/.env`);
  console.log(`  4. Fund agent wallet with testnet KITE`);
  console.log(`  5. npx hardhat run scripts/set-agent.js --network kite_testnet`);
  console.log(`  6. cd frontend && npm run dev`);
  console.log(`  7. cd agent && npm start\n`);
}

main().then(() => process.exit(0)).catch((err) => { console.error("❌", err); process.exit(1); });
